import Link from "next/link";
import { getPages } from "@/sanity/sanity-utils";
import "../globals.css";
import { Inter } from "next/font/google";

export const metadata = {
  title: "MyWebVerse",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pages = await getPages();

  return (
    <html lang="en">
      <body className={`max-w-3xl mx-auto py-8 ${inter.variable} font-sans`}>
        <header className="flex items-center justify-between">
          <Link
            href="/"
            className="bg-gradient-to-r from-pink-500 via-red-700 to-purple-600 bg-clip-text text-transparent text-lg font-bold px-4"
          >
            Fatmisko
          </Link>
          <div className="flex items-center gap-5 text-sm text-gray-600">
            {pages.map((page) => (
              <Link
                key={page._id}
                href={`/${page.slug}`}
                className="hover:underline font-bold"
              >
                {page.title}
              </Link>
            ))}
          </div>
        </header>
        <main className="py-16 px-4">{children}</main>
      </body>
    </html>
  );
}
